#!/usr/bin/python
import pandas as pd
import sys
import yaml

from garm.data_sources import LiveSource
from garm import Mailman
from garm import SignalChecker
from garm import Trader


if __name__ == "__main__":
    mailman = None
    with open(sys.argv[3], "r") as fin:
        conf = yaml.load(fin)
        info = conf[sys.argv[4]]
        mailman = Mailman(info["user"], info["server"], info["user"],
                          info["password"])


    signal_checker = SignalChecker(sys.argv[1], sys.argv[2])
    trader = Trader()
    for price_row in LiveSource(sys.argv[1], sys.argv[2]):
        for signal_row in signal_checker.check(price_row):
            if signal_row is not None:
                opened, closed = trader.update(signal_row)
                if opened:
                    df = pd.DataFrame(opened)
                    mailman.send_content("New trade",
                                         ["dichodaemon@gmail.com"],
                                         df.to_html())
                    print df
                if closed:
                    df = pd.DataFrame(closed)
                    mailman.send_content("Closed trade",
                                         ["dichodaemon@gmail.com"],
                                         df.to_html())
                    print df
