#!/usr/bin/python
import pandas as pd
import sys
import yaml

from gilles.data_sources import LiveSource
from gilles import Mailman
from gilles import SignalChecker
from gilles import Trader


if __name__ == "__main__":
    mailman = None
    with open(sys.argv[3], "r") as fin:
        conf = yaml.load(fin)
        info = conf[sys.argv[4]]
        mailman = Mailman(info["user"], info["server"], info["user"],
                          info["password"])


    signal_checker = SignalChecker(sys.argv[1], sys.argv[2])
    trader = Trader(126000.0, 0.01)
    for price_row in LiveSource(sys.argv[1], sys.argv[2]):
        for signal_row in signal_checker.check(price_row):
            if signal_row is not None:
                opened, closed = trader.update(signal_row)
                if opened:
                    df = pd.DataFrame(opened)
                    mailman.send_content("New trade",
                                         ["dichodaemon@gmail.com"],
                                         df.to_html())
                    print df
                    all_open = []
                    for pair_open in trader.open.values():
                        all_open.extend(pair_open)
                    df = pd.DataFrame(all_open)
                    df["idx"] = df["entry_time"]
                    df.set_index("idx", inplace=True)
                    df.sort_index(level=0, inplace=True)
                    df.to_csv(sys.argv[5])
                if closed:
                    df = pd.DataFrame(closed)
                    mailman.send_content("Closed trade",
                                         ["dichodaemon@gmail.com"],
                                         df.to_html())
                    df = pd.DataFrame(trader.closed)
                    df["idx"] = df["entry_time"]
                    df.set_index("idx")
                    df.sort_index(level=0, inplace=True)
                    df.to_csv(sys.argv[6])

